### ISSUE TITLE
Is it possible to describe views without using JSX?

### ISSUE THREAD

**Issue by achou11** [WorldMaker/butterfloat#72]
Apologies if this is documented somewhere - I couldn't find anything that directly answered this question when looking through the docs. While I don't mind JSX, I'm curious if there's some sort of hyperscript function (e.g. `h(...)`) or a template literal alternative to using JSX that's available, in order to provide some more utility in a less build-time reliant setup.

Awesome project btw! Resonates a lot with something I've been interested in exploring (i.e. reactive streams feeding into more granular DOM transformations as opposed to using a virtual DOM).

**Comment by WorldMaker** [comment]
Thanks for the question and for the compliment!

You can use the [`jsx(...)` function](https://worldmaker.net/butterfloat/#/types/modules?id=jsx) directly as roughly `h`-like. You will currently miss out on a lot of useful additional type information (one of the reasons for JSX here is *very strong* type safety/help that is somewhat unique to JSX and harder to do than things like template literals, it is one of the reasons I tend to use TSX as the name more than not in the documentation), but presumably one of the factors to write `jsx()` function calls directly may be to avoid a Typescript compile pass in some situation, so it may be be a fine trade-off in that situation.

I suppose it is not directly documented that the `jsx()` function can be directly used `h`-style, because I think of TSX as only syntax sugar for `jsx()`. That's an interesting "everyone knows" blindspot. Thanks for mentioning it, I will think about where there's a good place to explicitly mention it in the documentation.

**Comment by achou11** [comment]
great! that's good to know that you can use the jsx as a function. I actually typically assumed in the past that jsx was basically syntax sugar for h-like functions, but recently learned that that's technically not always the case so didn't want to wrongly assume it here.

**Comment by WorldMaker** [comment]
Yeah, the babel plugins that support JSX have done all sorts of crazy things over the years. From a Typescript perspective, Typescript has always just compiled it to function calls and only function calls. (Typescript from my understanding has done a lot to try to keep JSX simple.) The biggest differences that Typescript allows is what those functions are called (`React.createElement` versus `jsx` versus `h` versus whatever else; `React.Fragment` versus `Fragment`) and whether or not they are auto-imported (which unfortunately has been extremely React-specific and kind of dumb; even if I didn't prefer the explicit import statements, it's a lot of work for little gain to pretend to be React's weird experimental library to try to get auto-imports to work).

**Comment by WorldMaker** [comment]
I added a (hidden-by-default) [TSX Alternatives](https://worldmaker.net/butterfloat/#/getting-started?id=tsx-alternatives) section directly in the Getting Started page. Please let me know if you have improvements or other suggestions. Thanks again for the feedback.
